# Generated by Django 4.2.2 on 2023-07-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.skill'),
        ),
    ]
