# Generated by Django 4.2.2 on 2023-07-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_skill_my_field_vacancy_required_work_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='my_field',
            field=models.CharField(choices=[('full time work', 'полный рабочий день'), ('part-time employment', 'частичная занятость'), ('piecework', 'сдельная работа')], default='full time work', max_length=20),
        ),
    ]
