# Generated by Django 4.2.2 on 2023-07-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vacancy_my_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='my_field',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(choices=[('full time work', 'полный рабочий день'), ('part-time employment', 'частичная занятость'), ('piecework', 'сдельная работа')], default='full time work', max_length=20, verbose_name='Занятость'),
        ),
    ]
