# Generated by Django 4.2.3 on 2023-07-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_vacancy_my_field_vacancy_employment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='skill',
            field=models.CharField(choices=[('junior', 'junior'), ('middle', 'middle'), ('senior', 'senior')], default='junior', max_length=20, verbose_name='Навыки'),
        ),
    ]
