# Generated by Django 4.2.3 on 2023-08-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_resume_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='name',
        ),
    ]
